spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/housekeeping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '071126'
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

#    修改端口
server:
  port: 80
#  日志记录级别
logging:
  level:
    com.Wang: debug
    org.springframework: info
mybatis:
  #  实体名别名包
  type-aliases-package: com.wang.house.pojo
  #  映射文件路径
#  mapper-locations: classpath:mapper/*.xml
  #  日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 分页插件配置
pagehelper:
  properties:
    helper-dialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params:
      count: countSql
